export const CREATE_POST = 'CREATE_POST';
export const GET_POSTS = 'GET_POSTS';
export const SET_IS_UPLOADING = 'SET_IS_UPLOADING';
export const SET_TRANSFERRED = 'SET_TRANSFERRED';
export const SET_ERROR_UPLOAD = 'SET_ERROR_UPLOAD';
